---
# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

lint:rubocop:
  image: ruby
  script:
    - gem install rubocop -N
    - rubocop lib

.test:
  before_script:
    - sed -e 's/# gem /gem /' -i Gemfile
    - gem install bundler -N
    - bundle install -j $(nproc) --path vendor
  coverage: '/\((\d+(?:.\d+)?)\%\) covered/'
  script:
    - bundle exec rake test
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/

test:ruby2.7:
  extends: .test
  image: "ruby:2.7"

test:ruby3.0:
  extends: .test
  image: "ruby:3.0"

test:ruby3.1:
  extends: .test
  image: "ruby:3.1"

pages:
  image: ruby
  stage: deploy
  needs: []
  script:
    - gem install yard -N
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
  when: always
